env:
- CXX=g++-4.8
language: node_js
node_js:
- '6.1'
script: npm run test
deploy:
  provider: heroku
  app: youtube-search-app
  api_key:
    secure: lxYsJT3HjMqndcd8F5uaHvzQmMlJnea5SAyqQPyxgP9tSPzJQqXXARQrXhKSbYo5Y3wfu5DoZPXfoLppt6UkTIy15n7hZrW1DU8m8ORY+G5ZIjiWFMdCCtLVwCfQ/xvWHktZqqkUfpywjL1qzszCdkS2SkrwMoCpT6ZrsOz4KtZ3Y92CQ5c53D4Oi0sT+RAx14oO+bnQ/sfRWsoyzy53NB40LegdLktlIf7OVDj1hnFmWaX7VumvmwiwwZaiqG1gV43n7TtmP2/NNPCLafH+o55gwfJ8elzwoQFgB53DHzjPc7q0zE+OwLc8L0qlOpjCJRJnuHqUtBK41Sq3KetnV+pJcW9YbvQtEGKGVI46cOTKIP0K/g4TN+47341MKJdgiJ39O4rBp7SxyyOlFjenALKmO47yb9zAjK2XFKBfo4I/EMmbh7rymf6esJJRAE6rgqYaf2jxZGLZRo8zQahyJQQsQmDUzDgEN5ZbxqkKHPUhqCoExDiYf8rlOY0l7ClIqLLq04YVX3xy6ixq+yD5pk4e9Mx5kVF99dyVXQTyIhK7TQK7agFAb3bgqMvk1t9LyZ+lLmgU8zh/P6uIoSn4aJnPu0h8+wHIMGlsShn8ptZRGF0ThLdGXkJlrTvInwAU82NR3YQd7gBr7f/F1pIAXEc4+Q3bP6cUAM4/XbLVz9w=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8

