env:
- CXX=g++-4.8
language: node_js
node_js:
- '6.1'
script: npm run test
deploy:
  provider: heroku
  app: rogue-dungeon-explorer
  api_key:
    secure: HIIgP3opoF1zhwnqcqfrFuF4ash1rwWsDUe8GKKwz6B5DPe5kQR86o2eveRs9z1J38UzzRsFTSXeMXM3xg45KoHqGzsBqgmTNwHwKo5Sj1AuiiW79dlwJh5XNrrQGsI2BZNyu63Pa/tZAqkNXcCrZNRK6NpR4W5p92cAg2UshLA2oiNg2q4eEHWTMzcEUNtwwrmKjLPEp6PESAHBOixl3DXLqsZFuqhJ948R5fmIu67pzgYz5zH/UMkXR2wy8rs35vSY/l0Ba+DmpkBqiYjT9EbsnV/caKTFM+IFwd4Db8aG5baRI9uXIy1Nl8ye8t1+VUx1KD32lFs2zTFrUA9/nL0QOLYhAJ0tXQsIRmEhW4h1m5m4N5evHUCq6yU2KpC0rwpdVQ9RLnOaY0NwGX1Pvhd7XW5xAPSNzp6PvV9mM1AP2VmRVxkRKkFwRsSxjCp9+LUxFBghjrmfBBYs4lapRvKbSH+HiAVqKtMlW8hSoHf10YgvuOF6NUgrQIyUG6i2z44CeIfc/oADpMQbS36bC/0jDNdobdnWj+GB4w22gSF0L1ntfIuDSgGdQe7plPw/qY3p6XD4JBoLsFY9jY+w1QKgmVvL/PXeIyd2MjkigAeVlB7mKOgJ8Cm7ihPf1COXy/h+V9l59ObVFItea4Jzt0qEEGMi4vJFHmoszZoa5KM=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8